from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

zakaz_buttonlar = ReplyKeyboardMarkup(
    keyboard=[
        [
            KeyboardButton(text='Альметьевск')
        ],
        [
            KeyboardButton(text='Анапа')
        ],
        [
            KeyboardButton(text='Артем')
        ],
        [
            KeyboardButton(text='Александров')
        ],
        [
            KeyboardButton(text='Архенгельск')
        ],
        [
            KeyboardButton(text='Асбест')
        ],
        [
            KeyboardButton(text='Астрахань')
        ],
        [
            KeyboardButton(text='Ачинск')
        ],
        [
            KeyboardButton(text='Балашиха')
        ],
        [
            KeyboardButton(text='Балашов')
        ],
        [
            KeyboardButton(text='Барнаул')
        ],
        [
            KeyboardButton(text='Батайск')
        ],
        [
            KeyboardButton(text='Белгород')
        ],
        [
            KeyboardButton(text='Белово')
        ],
        [
            KeyboardButton(text='Белогорск(Амурская обл)')
        ],
        [
            KeyboardButton(text='Белорецк')
        ],
        [
            KeyboardButton(text='Белореченск')
        ],
        [
            KeyboardButton(text='Бердск')
        ],
        [
            KeyboardButton(text='Березники')
        ],
        [
            KeyboardButton(text='Березовский(Сврдл обл)')
        ],
        [
            KeyboardButton(text='Бийск')
        ],
        [
            KeyboardButton(text='Биробиджан')
        ],
        [
            KeyboardButton(text='Благовещенск (Амурская обл)')
        ],
        [
            KeyboardButton(text='Борисоглебск')
        ],
        [
            KeyboardButton(text='Боровичи')
        ],
        [
            KeyboardButton(text='Братск')
        ],
        [
            KeyboardButton(text='Брянск')
        ],
        [
            KeyboardButton(text='Бугульма')
        ],
        [
            KeyboardButton(text='Буденновск')
        ],
        [
            KeyboardButton(text='Бузулук')
        ],
        [
            KeyboardButton(text='Великие Луки')
        ],
        [
            KeyboardButton(text='Великий Новгород')
        ],
        [
            KeyboardButton(text='Верхняя Пышма')
        ],
        [
            KeyboardButton(text='Видное')
        ],
        [
            KeyboardButton(text='Владивосток')
        ],
        [
            KeyboardButton(text='Владикавказ')
        ],
        [
            KeyboardButton(text='Владимир')
        ],
        [
            KeyboardButton(text='Волгоград')
        ],
        [
            KeyboardButton(text='Волгодонск')
        ],
        [
            KeyboardButton(text='Волжск')
        ],
        [
            KeyboardButton(text='Вологда')
        ],
        [
            KeyboardButton(text='Волжский')
        ],
        [
            KeyboardButton(text='Вольск')
        ],
        [
            KeyboardButton(text='Воркута')
        ],
        [
            KeyboardButton(text='Воскресенск')
        ],
        [
            KeyboardButton(text='Воткинск')
        ],
        [
            KeyboardButton(text='Всеволожск')
        ],
        [
            KeyboardButton(text='Выборг')
        ],
        [
            KeyboardButton(text='Вязьма')
        ],
        [
            KeyboardButton(text='Гатчина')
        ],
        [
            KeyboardButton(text='Гатчина')
        ],
        [
            KeyboardButton(text='Георгиевск')
        ],
        [
            KeyboardButton(text='Горно-Алтайск')
        ],
        [
            KeyboardButton(text='Губкин')
        ],
        [
            KeyboardButton(text='Гуково')
        ],
        [
            KeyboardButton(text='Густь-Хрустальный')
        ],
        [
            KeyboardButton(text='Дербент')
        ],
        [
            KeyboardButton(text='Дзержинск')
        ],
        [
            KeyboardButton(text='Дмитров')
        ],
        [
            KeyboardButton(text='Долгопрудный')
        ],
        [
            KeyboardButton(text='Донской')
        ],
        [
            KeyboardButton(text='Дубна')
        ],
        [
            KeyboardButton(text='Евпатория')
        ],
        [
            KeyboardButton(text='Егорьевск')
        ],
        [
            KeyboardButton(text='Ейск')
        ],
        [
            KeyboardButton(text='Екатеринбург')
        ],
        [
            KeyboardButton(text='Елабуга')
        ],
        [
            KeyboardButton(text='Елец')
        ],
        [
            KeyboardButton(text='Ессентуки')
        ],
        [
            KeyboardButton(text='Железногорск(Красноя край)')
        ],
        [
            KeyboardButton(text='Железногорск (Курская обл)')
        ],
        [
            KeyboardButton(text='Жигулевск')
        ],
        [
            KeyboardButton(text='Жуковский')
        ],
        [
            KeyboardButton(text='Заречный')
        ],
        [
            KeyboardButton(text='Зеленогорск')
        ],
        [
            KeyboardButton(text='Зеленодольск')
        ],
        [
            KeyboardButton(text='Златоуст')
        ],
[
            KeyboardButton(text='Иваново')
        ],
        [
            KeyboardButton(text='Ивантеевка')
        ],
        [
            KeyboardButton(text='Ижевск')
        ],
        [
            KeyboardButton(text='Избербаш')
        ],
        [
            KeyboardButton(text='Иркутск')
        ],
        [
            KeyboardButton(text='Искитим')
        ],
        [
            KeyboardButton(text='Ишим')
        ],
        [
            KeyboardButton(text='Ишимбай')
        ],
        [
            KeyboardButton(text='Йошкар-Ола')
        ],
        [
            KeyboardButton(text='Казань')
        ],
        [
            KeyboardButton(text='Калининград')
        ],
        [
            KeyboardButton(text='Каменск- Уральский')
        ],
        [
            KeyboardButton(text='Каменск - Шахтинский')
        ],
        [
            KeyboardButton(text='Камышин')
        ],
        [
            KeyboardButton(text='Канск')
        ],
        [
            KeyboardButton(text='Каспийск')
        ],
        [
            KeyboardButton(text='Асбест')
        ],
        [
            KeyboardButton(text='Астрахань')
        ],
        [
            KeyboardButton(text='Ачинск')
        ],
        [
            KeyboardButton(text='Балашиха')
        ],
        [
            KeyboardButton(text='Балашов')
        ],
        [
            KeyboardButton(text='Барнаул')
        ],
        [
            KeyboardButton(text='Батайск')
        ],
        [
            KeyboardButton(text='Белгород')
        ],
        [
            KeyboardButton(text='Белово')
        ],
        [
            KeyboardButton(text='Белогорск(Амурская обл)')
        ],
        [
            KeyboardButton(text='Белорецк')
        ],
        [
            KeyboardButton(text='Белореченск')
        ],
        [
            KeyboardButton(text='Бердск')
        ],
        [
            KeyboardButton(text='Березники')
        ],
        [
            KeyboardButton(text='🔙 Назад'),
            KeyboardButton(text='🔝 Главное Меню')
        ]
    ]
)